# Generated by Django 5.0.2 on 2024-03-29 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workout_name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BP', 'Bench Press'), ('LP', 'Leg Press'), ('SQ', 'Squat'), ('SP', 'DB Shoulder Press'), ('SM', 'Standing Military'), ('DL', 'Deadlift'), ('PL', 'Pull Ups'), ('ID', 'Incline DB'), ('IB', 'Incline Barbell'), ('OT', 'Other')], default='OT', max_length=100)),
                ('custom_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gymapp.workoutsession')),
            ],
        ),
    ]
