# Generated by Django 5.0.2 on 2024-04-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_remove_customuser_address_remove_customuser_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('BP', 'Bench Press'), ('LP', 'Leg Press'), ('SQ', 'Squat'), ('SP', 'DB Shoulder Press'), ('SM', 'Standing Military'), ('DL', 'Deadlift'), ('PL', 'Pull Ups'), ('ID', 'Incline DB'), ('IB', 'Incline Barbell'), ('OT', 'Other')], default='BP', max_length=100),
        ),
        migrations.CreateModel(
            name='ExerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='gymapp.exercise')),
            ],
        ),
    ]
