# Generated by Django 5.0.2 on 2024-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_remove_exercise_reps_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
